# Generated by Django 3.2.14 on 2022-07-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='logo',
            new_name='image',
        ),
    ]
